name: Publish Docker Image

on:
  release:
    types: [published]
#   push:
#     branches: ["release"]
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  build:
    name: Publish Docker Image to Docker Hub and GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: |
          thorelectronics/website
          ghcr.io/${{ github.repository }}
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.3.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
